### PR TITLE
Simplify travis.yml, add tests for 3.7 & Django 2.1

### PR DESCRIPTION
**Pull request by xavfernandez**

### CODE REVIEW

**Comment by xavfernandez** [comment]
All green, cc @vdboor @yakky

**Comment by valberg** [comment]
Maybe add django 2.2 as well?

**Comment by xavfernandez** [comment]
Django 2.2 crashes :)
It should be added via #242 or #246

**Comment by valberg** [comment]
Yay! Awesome @vdboor

**Pull request merged**
