### PR TITLE
Add docs for deleting translations

### LINKED ISSUE #143: How do I delete a translation
Hi, I'm importing translations from an XML file and certain translations are marked up like this:

```
<name lang="de">Hi</name>
```

The tag can occur multiple times. So when I import these translations I need to update existing ones, create new ones and delete non occuring ones. 

I know how I update and create translations, but how do I delete a translation?

### PR DESCRIPTION
**Pull request by BernhardPosselt**
Fix #143

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
PS: do you also need this in the REAMDE?

**Comment by vdboor** [comment]
I'm sorry, I'm closing this in favor for a better API solution that also works for users of multiple inheritance.

**Comment by BernhardPosselt** [comment]
Ok, no worries :)

Just wanted to give you a helping hand since maintaining things is hard and labor intensive ;D

**Comment by vdboor** [comment]
Thanks, that is much appreciated. It's indeed a lot of work. A `delete_translation()` API is now available in 83dda28f24d9696df84ddd245cac5ab4757447f3

**Pull request closed without merging**
