### PR TITLE
Test polymorphic

### PR DESCRIPTION
**Pull request by jrief**
This is just to prove that #51 really causes a problem.
I just added the [example code from the docs](http://django-parler.readthedocs.org/en/latest/advanced/polymorphicmodel.html), but the result is the same. If I run the unit test, I get:

```
File "../lib/python2.7/site-packages/django/db/models/fields/related.py", line 1259, in set_field_name
    self.field_name = self.field_name or self.to._meta.pk.name
AttributeError: 'NoneType' object has no attribute 'name'
```

Unfortunately I have no idea where to fix that. Can you please give me some hints. I reported this issue in November 2014 and it prevents me from migrating to Django-1.7 and further.

### CODE REVIEW

**Comment by jrief** [comment]
See https://travis-ci.org/edoburu/django-parler/jobs/64733375
Whats interesting, it works well with Python-3.

**Comment by vdboor** [comment]
Hi! Thanks for providing this - this really helps debugging it.

I've been looking into it briefly, and it seems that switching the inheritance order does have effect. You can see that at 238cc97e47257d2f83ba38d73bd8e973bcf7fb43 In the other ordering, I got an SQL query error.

**Comment by vdboor** [comment]
FYI, I merged all your commits, but rebased them first to get rid of the additional upstream merges.

**Comment by vdboor** [comment]
Your test can be found in the custom branch: https://github.com/edoburu/django-parler/compare/jrief-test-polymorphic since that needs further testing

**Pull request closed without merging**
