### PR TITLE
Automatically save data at language tab switch

### PR DESCRIPTION
**Pull request by Vadim-Karpenko**
Sometimes I forget to save all my fields at the language switch and to prevent this in the future all of your data will be saved automatically.

### CODE REVIEW

**Comment by Vadim-Karpenko** [comment]
Note: to enable autosave on model creation you need to include this following code in admins.py:
```
def response_add(self, request, obj, post_url_continue=None):
        next_href = request.GET.get('next_href', None)
        app_name = "<YOUR APPLICATION NAME>"
        model_name = "<YOUR MODEL NAME>"
        if next_href:
            return redirect(f'/admin/{app_name}/{model_name}/{obj.id}/change/?language={next_href}')
        else:
            return super().response_add(request, obj, post_url_continue)
```

**Comment by jrief** [comment]
User interfaces shall be predictable. Saving content implicitly after clicking on another tab, contradicts good user experience. Therefore I oppose against this pull request.

Your use-case is perfectly valid. How about rendering a warning box, if the user attempts to change the language before saving the content?

**Comment by Vadim-Karpenko** [comment]
For new update when it check for errors at the tab switch, it also needs this code in admins.py for every admin classes -
```
Maybe would be better to make something like Mixin to make it automatically enabled just with one line of code.

**Comment by Vadim-Karpenko** [comment]
> User interfaces shall be predictable. Saving content implicitly after clicking on another tab, contradicts good user experience. Therefore I oppose against this pull request.
> 
> Your use-case is perfectly valid. How about rendering a warning box, if the user attempts to change the language before saving the content?

I agree it's a little bit not predictable, and the warning box would be a good enough. But to minimize this issue I have changed **language_tabs.html** to display some hint (not included in the current pull request).
bandicam 2019-01-05 01-30-08-227
Let me know if this will change you point of view.

Thanks

**Comment by jrief** [comment]
I believe that with a little bit of Javascript code, it is perfectly possible to add a warning box. Simply use the `onbeforeonload` event as described [here](https://stackoverflow.com/questions/1704533/intercept-page-exit-event).

**Comment by vdboor** [comment]
I agree with @jrief here, this is not the right way to implement this. A warning box would be way better.
Also how would you deal with form errors on switching? ;-)

**Pull request closed without merging**
