### PR TITLE
use external six (django 3.0 compatibility)

### PR DESCRIPTION
**Pull request by xi**
`django.utils.six` and `django.utils.encoding.python_2_unicode_compatible` are removed in django 3:

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

### CODE REVIEW

**Comment by valberg** [comment]
The django project are encouraging third party apps to drop support for anything prior to django 2.2 when 3.0 is released (https://docs.djangoproject.com/en/3.0/releases/3.0/#third-party-library-support-for-older-version-of-django). 

I would suggest we follow that advice and get rid of using six at all.

Just my two cents :)

**Comment by xi** [comment]
> I would suggest we follow that advice and get rid of using six at all.

I mostly agree. Still I think this is a useful first step.

**Comment by xi** [comment]
Django 3.0 has been released an this is the only thing that is keeping me from updating. Is there anything I can do to help get this merged?

**Comment by vdboor** [comment]
Thanks for the PR! I've merged this (locally because of conflicts). These changes are now in master!

**Comment by wlonk** [comment]
Can we get an ETA on a new release so we can update projects that use this to Django 3? No rush, just curious for my own ability to plan. Thanks!

**Comment by vdboor** [comment]
I've released a 2.0.1 version a few days ago that contains these changes!

**Pull request closed without merging**
